### PR TITLE
Add HyFetch

### PR DESCRIPTION
**Pull request by Kaiddd**
HyFetch is a fork of neofetch that addresses most pull requests and issues on the original neofetch repository, as neofetch is now unmaintained. It also includes pride flags!

https://github.com/hykilpikonna/hyfetch

### CODE REVIEW

**Comment by Kaiddd** [comment]
I'd normally agree with this, but neofetch has not had a commit in over 2 years, and HyFetch has currently 957 commits since the end of neofetch, last one being yesterday

**Comment by Kaiddd** [comment]
Would also like to add that multiple fetches in the current list directly call themselves neofetch clones or use the wording "Neofetch but..."

**Comment by siduck** [comment]
> Would also like to add that multiple fetches in the current list directly call themselves neofetch clones or use the wording "Neofetch but..."

if you look close, those aren't neofetch forks. Some of them are just rewrites in different languages & have different functionalities and using neofetch wording isnt a problem as people are more familiar with the word "neofetch" than the word  "fetch tool"

**Comment by Kaiddd** [comment]
Well at that point I can argue that HyFetch is 50% coded in python, whilst neofetch is in bash, but I won't argue, it is your repo haha

**Comment by Luciogi** [comment]
why not pfetch

**Comment by zakarrrr** [comment]
Thank God this wasnt added, filthy lgtv stuff lol

**Pull request closed without merging**
