### PR TITLE
Added themes section, some conky themes

### PR DESCRIPTION
**Pull request by george-gca**

### CODE REVIEW

**Comment by Sparkenstein** [comment]
Closebox has went dark, can't merge this

**Comment by george-gca** [comment]
Why did he went dark? He was one of the best theme makers I ever seen. It is a pity.

**Comment by george-gca** [comment]
Left only reddit conkyporn (yes, this is the name) community link.

**Comment by george-gca** [comment]
@Sparkenstein

**Comment by Sparkenstein** [comment]
dayum alright, this works

**Review by Sparkenstein — APPROVED** [review]

**Pull request merged**
