### PR TITLE
remove hfetch

### PR DESCRIPTION
**Pull request by gentoo-btw**
hfetch was definitely a total disaster.
I wish I never would make another horrible fetch tool again.

### CODE REVIEW

**Review by siduck — APPROVED** [review]

**Comment by siduck** [comment]
@gentoo-btw what happened?

**Comment by gentoo-btw** [comment]
> @gentoo-btw what happened?

my bash code looks like it was written by a first-time bash programmer. and it didn't get many upvotes on reddit. just a 100 and many other fetches can achieve more than that. and I commented in a app called kusa. also with about the fetch tool. and it got -10+ downvotes. and the fetch tool barley didn't get any cloners. there was like 50+ visitors and I got only 2-4 clones.

**Comment by gentoo-btw** [comment]
you can also check out my list of gruvbox ports.
https://github.com/gentoo-btw/awesome-gruvbox

**Comment by siduck** [comment]
@gentoo-btw a program's popularity shouldnt matter anyways!! if it worked fine then you dont have to remove it :)

**Comment by gentoo-btw** [comment]
> @gentoo-btw a program's popularity shouldnt matter anyways!! if it worked fine then you dont have to remove it :)

i just had problems with my fetch tool. maybe one day i will create a good-looking fetch tool.

**Pull request merged**
