### PR TITLE
why not add reviewdog?

### PR DESCRIPTION
**Pull request by gentoo-btw**
i think you have to install this first https://github.com/apps/reviewdog

### CODE REVIEW

**Comment by siduck** [comment]
this is a simple repo, why do we need it here? :thinking:

**Comment by gentoo-btw** [comment]
> this is a simple repo, why do we need it here? 🤔

because maybe the edits might have something wrong.

**Comment by siduck** [comment]
@gentoo-btw still! i'll check PR's carefully next time so we dont need this .

**Comment by gentoo-btw** [comment]
> @gentoo-btw still! i'll check PR's carefully next time so we dont need this .

alright

**Pull request closed without merging**
